//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prenotazione
    {
        public int ID { get; set; }
        public int PrenotazioneRisorsa { get; set; }
        public string Descrizione { get; set; }
        public Nullable<System.DateTime> DataInizio { get; set; }
        public Nullable<System.DateTime> DataFine { get; set; }
        public Nullable<int> PrenotazioneEvento { get; set; }
        public Nullable<int> PrenotazioneSala { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual Risorsa Risorsa { get; set; }
    }
}
